### ISSUE TITLE
文档编写事项

### ISSUE THREAD

**Issue by satgo1546** [IcebergOS/frogimine#12]
由于最初只是作为一个爱好制作（现在依旧是这样），所以一切commit message都使用了中文。Wiki页面也应使用中文书写。

所以，这个是为什么？
https://github.com/IcebergOS/frogimine/wiki/Design/88d1e100274c5dfa3fa427cf990a471561efbd9f

---

关于本地化：这个操作系统应当内部可以切换用户界面的语言。但源代码是中文的。（为啥？）

---

由于爱好制作的原因，我不希望它变得非常复杂：我们应该只支持32位（“所以说不要乱搞”），然后把目录结构中的${ARCH}删掉。对此，征求一些意见。

---

另外，hybird的正确拼写是hybrid……

**Comment by bobcao3** [comment]
迟早要翻译233，文档部分会慢慢地搞成全部双语，然后ARCH目录的存在也让多架构可能的同时足够简化，目前我们ARCH里只会有i686，也许一年后就会有amd64或者armv7el之类的

**Comment by bobcao3** [comment]
然后源代码里面的语言额。。。其实我偏向写英文因为很多单词中文没有办法说的好（就说我不知道中文好了）

**Comment by satgo1546** [comment]
因为以前我从来没想过要英文化，是作为永远不用英文化的项目做的。

如果ARCH要扩展的话，就没有问题了。

表示我日常即使是计算机术语也用中文的，极少数才会用英文（比如：~~commit~~ 提交、~~session~~ 会话），所以很喜欢用中文。

**Comment by satgo1546** [comment]
还有，参照这几个提交： 685c1bc84158deefaabb71c12325263614634433 、 b042775852d4ce91725a9ad06f9ee2e20a9feb18 、 051f63b9a307a5fc7906df7188059cf04ccb2422 、 1635df69f68ccd2675f888ab5dd4593325d3c5e4 。

**Comment by bobcao3** [comment]
代码的本地化以后再说了，但是Wiki还是语言通用的为好，我在翻译中

**Comment by bobcao3** [comment]
Design翻译完成了

**Comment by bobcao3** [comment]
（顺便关注下Moxtra里面的那个gh消息推送

**Comment by satgo1546** [comment]
等、等等？

这样的话，先把现有的几个页面加上“zh-Hans”的前缀。

**Comment by bobcao3** [comment]
这样吧你去翻译代码规范到英文放在下面，我把Contributing也翻译，（像design那样对照最好）

**Comment by satgo1546** [comment]
为啥要对照啊……看中文的看中文，看英文的看英文……

**Comment by bobcao3** [comment]
e..你去看一下Design那页
实际上是分开的

**Comment by satgo1546** [comment]
这样的话，以后语言多了的话，一页会很长。

**Comment by bobcao3** [comment]
。。你去整理吧，我先把翻译填完

**Comment by satgo1546** [comment]
而且不利于检查历史记录之类的

**Comment by satgo1546** [comment]
好吧，你翻译填完了我把wiki理一下……

**Comment by bobcao3** [comment]
design，license这两个已经完成了

**Comment by bobcao3** [comment]
contributing完成翻译
