### ISSUE TITLE
突然发现这没有license

### ISSUE THREAD

**Issue by bobcao3** [IcebergOS/frogimine#4]
等着被人无条件抄袭占有。。。？
建议放Apache License
（（（（（（（（（（（（（（不要GPL!!!!!!!!!!!!!也不要gnu的任何协议，，，，，作为个bsd党，gnu就是＊＊）））））））））））））））

**Comment by satgo1546** [comment]
我是准备用Apache License的，然而因为一些原因（懒），一直没弄。

另外，貌似没有协议 = 保留所有权利？

**Comment by satgo1546** [comment]
LICENSE创建完毕。
