### ISSUE TITLE
是不是可以Transfer了

### ISSUE THREAD

**Issue by bobcao3** [IcebergOS/frogimine#7]
IcebergOS那边的库已经清除了

**Comment by satgo1546** [comment]
正在处理中。

**Comment by satgo1546** [comment]
出了点问题，重试中……

**Comment by satgo1546** [comment]
仓库转移完毕！

**Comment by bobcao3** [comment]
然后vga驱动你有想法么？（（（vga这边我是一头雾水

在 2016-01-23 21:09:24，"Frog Chen" notifications@github.com 写道：

Closed #7.

**Comment by satgo1546** [comment]
@bobcao3 貌似你回复错邮件了……

**Comment by bobcao3** [comment]
然后现在最好开develop branch，master放着不动，我已经开了bobcao3-develop

在 2016-01-23 21:09:24，"Frog Chen" notifications@github.com 写道：

Closed #7.

**Comment by satgo1546** [comment]
这个问题还是写一个CONTRIBUTING.md比较好。

**Comment by bobcao3** [comment]
顺便你先别开branch，我先整理代码结构

**Comment by satgo1546** [comment]
好的。

**Comment by satgo1546** [comment]
另外，有关代码注释的问题……我写个COMMENTING.md算了:sweat:

**Comment by bobcao3** [comment]
ok

**Comment by bobcao3** [comment]
merge好了，你可以开develop分支了

**Comment by bobcao3** [comment]
顺便开个doc文件夹放这堆md

**Comment by satgo1546** [comment]
直接用GitHub的wiki不就好了

**Comment by bobcao3** [comment]
对哦233333333
