### ISSUE TITLE
“Copyright owner”是啥呢？

### ISSUE THREAD

**Issue by satgo1546** [IcebergOS/frogimine#8]
在Apache License里面，要求这个字段。

> Copyright {yyyy} {name of copyright owner}

**Comment by satgo1546** [comment]
在没有转移仓库之前，应该是“satgo1546”或“Frog Chen”。然而现在已经不是这样了，所以需要IcebergOS的一般名称（即，可以含有空格、正确的大小写的名称）。

**Comment by bobcao3** [comment]
Wiki上放了，在wiki的footer

**Comment by bobcao3** [comment]
顺便Wiki的右边License部分也有了
